site_name: Fiware-iotagent-lwm2m


site_url: https://fiware-iotagent-ul.readthedocs.org

repo_url: https://github.com/telefonicaid/iotagent-lwm2m.git

site_description: IoT Agent LWM2M (CoAP/UDP transport) Documentation

docs_dir: /

site_dir: html

markdown_extensions: [toc,fenced_code]

use_directory_urls: false

theme: readthedocs

extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]

pages:

- Home: README.md

- 'User & Programmers Manual':

- ‘Intro & Development guide’: ‘docs/userGuide.md’

- ‘API Walkthrough & Device provisioning’: ‘docs/deviceProvisioning.md’

- ‘Operation with Static configuration’: ‘docs/staticConfiguration.md’

- ‘Operation with Provisioning configuration’: ‘docs/configurationProvisioning.md’

- 'Docker': ‘Dockerfile’

- 'Installation & Administration Manual': ‘docs/administrationGuide.md.md’


